# Naive Bayes

In [15]:
import numpy as np  
import pandas as pd

In [16]:
data = pd.read_csv('E:\BRAINWORk\Machine Learning\placement-project\DataSets\play_tennis.csv')
data

<>:1: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
<>:1: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
C:\Users\Snehal\AppData\Local\Temp\ipykernel_22124\470883137.py:1: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
  data = pd.read_csv('E:\BRAINWORk\Machine Learning\placement-project\DataSets\play_tennis.csv')

     Outlook Temperature Humidity    Wind Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [17]:
data.head()

    Outlook Temperature Humidity    Wind Play
0     Sunny         Hot     High    Weak   No
1     Sunny         Hot     High  Strong   No
2  Overcast         Hot     High    Weak  Yes
3      Rain        Mild     High    Weak  Yes
4      Rain        Cool   Normal    Weak  Yes

In [18]:
# Problem 1

# outlook= Sunny, Temp=Hot, Humidity=High, wind=weak
# play or no play ?

In [19]:
# Solution

# P(Yes / Sunny, Hot, High, Weak) = P(Sunny / yes) * P(Hot / Yes) * P(High / Yes) * P(Weak / Yes) * p(Yes)

# P(No / Sunny, Hot, High, Weak) = P(Sunny / No) * P(Hot / No) * P(High / No) * P(No)

# Compare and decide using the maximum a posteriori rule

In [20]:
# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak
# Play or No Play?

In [21]:
# Solution

# P(Yes | Overcast,Cold,Low,Weak)=P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes)
# P(No | Overcast,Cold,Low,Weak)=P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No)

# Compare and decide using the Maximum a posteriori rule

In [22]:
# Training

# Lookup table (dictionary)

# Testing

In [23]:
# p(yes)
# p(No)

In [28]:
print(data.columns.tolist())

['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play']

In [29]:
data['Play'].value_counts()

Play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
# Probablity of yes and no

py=9/14
pn=5/14

print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [32]:
# Outlook column

pd.crosstab(data['Outlook'], data['Play'])

Play      No  Yes
Outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [33]:
# Probability creation

Pon = 0    # p overcast n
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [34]:
# Temprature

pd.crosstab(data['Temperature'],data['Play'])

Play         No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [35]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [36]:
# Humidity

pd.crosstab(data['Humidity'],data['Play'])

Play      No  Yes
Humidity
High       4    3
Normal     1    6

In [37]:
PHighNo = 4/5
PNormalNo = 1/5
PHighYes = 3/9
PNormalYes = 6/9

In [38]:
# Wind

pd.crosstab(data['Wind'],data['Play'])

Play    No  Yes
Wind
Strong   3    3
Weak     2    6

In [39]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [40]:
# Problem 1
# outlook= Sunny, Temp=Hot, Humidity=High, wind=weak
# play or no play ?

Pyes = py*Psy*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [41]:
Pno = pn*Psn*PHotNo*PHighNo*PWeakNo
print(Pno)

0.02742857142857143